-   id: magento-phpcs
    name: PHP Code Sniffer
    description: PHP CodeSniffer is able to fix many errors and warnings automatically.
    entry: magento-phpcs
    language: python
-   id: magento-phpstan
    name: PHP Static Analysis Tool
    description: PHPStan is a static analysis system for PHP projects. It finds bugs in your codebase by inspecting the source files.
    entry: magento-phpstan
    language: python
    types: [php]
-   id: magento-webapi-rest-phpunit
    name: REST API PHPUnit test
    entry: magento-webapi-rest-phpunit
    language: python
    pass_filenames: false
    always_run: true
    args: ["-c=dev/tests/api-functional/phpunit_rest.xml"]
-   id: magento-webapi-soap-phpunit
    name: SOAP API PHPUnit test
    entry: magento-webapi-soap-phpunit
    language: python
    pass_filenames: false
    always_run: true
    args: ["-c=dev/tests/api-functional/phpunit_soap.xml"]
